export const FETCH_WEATHER: string = 'FETCH_WEATHER';
export const REQUESTED_WEATHER: string  = 'REQUESTED_WEATHER';
export const REQUESTED_WEATHER_SUCCESSED: string = 'REQUESTED_WEATHER_SUCCESSED';
export const REQUESTED_WEATHER_FAILED: string = 'REQUESTED_WEATHER_FAILED';