export const FETCH_ALL_POSTS_REQUESTED = 'FETCH_ALL_POSTS_REQUESTED';
export const FETCH_ALL_POSTS_FAILED = 'FETCH_ALL_POSTS_FAILED';
export const FETCH_ALL_POSTS_SUCCEEDED = 'FETCH_POSTS_SUCCEEDED';

export const FETCH_POST_REQUESTED = 'FETCH_POST_REQUESTED';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';
export const FETCH_POST_SUCCEEDED = 'FETCH_POST_SUCCEEDED';

export const CREATE_POST_REQUESTED = 'CREATE_POST_REQUESTED';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';
export const CREATE_POST_SUCCEEDED = 'CREATE_POST_SUCCEEDED';
