export const SAVE_COMMENT = 'SAVE_COMMENT'

export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'

export const CHANGE_AUTH = 'CHANGE_AUTH'