version: "3.7"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ./.env
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --auth